create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  buyer_name text not null,
  buyer_email text not null,
  buyer_phone text not null,
  property_name text not null,
  property_location text,
  property_price text,
  visit_date date,
  visit_time text,
  lead_status text,
  created_at timestamp with time zone default now()
);

alter table public.bookings enable row level security;

drop policy if exists "Allow public booking inserts" on public.bookings;
create policy "Allow public booking inserts"
on public.bookings
for insert
to anon
with check (true);
